signlas_3.1.o: signals_3.1.c
	gcc -c signals_3.1.c
	
signals_out: signals_3.1.o
	gcc -o signals_out signals_3.1.o

signlas_3.1.o: signals_3.1.c
	gcc -c signals_3.1.c
	
signals_out: signals_3.1.o
	gcc -o signals_out signals_3.1.o

signal_handler_32.o: signal_handler_32.c
	gcc -c signal_handler_32.c

sighand_out: signal_handler_32.o
	gcc -o sighand_out signal_handler_32.o

clean: 
	rm signals_out signals_3.1.o signal_handler_32.o sighand_out